version: '3.9'

services:
  db:
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: api-rate-limiting-main
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306 
  redis:
    image: redis
    ports:
    - "6379:6379"