CREATE TABLE IF NOT EXISTS user_rate (
	id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	user_limit INT(11) NOT NULL DEFAULT 0,
	CONSTRAINT user_rate_constr PRIMARY KEY (id)
);
